#!/usr/bin/env python3
"""Intrynx license tool (VENDOR-SIDE — keep the private key secret).

Workflow:
  1) one-time:  python3 tools/mint_license.py keygen
        → creates keys/intrynx_license_private.pem  (KEEP SECRET, never ship)
          and embeds the public key in security/embedded_key.py (shipped in probe)

  2) on the target machine, find its fingerprint:
        python3 agent.py hostid          # or: ./probe hostid

  3) mint a license for that machine:
        python3 tools/mint_license.py mint --customer "ACME Corp" \
            --host <fingerprint-from-step-2> --days 365 --name dmz-01
        → prints a PROBE_LICENSE token to paste into probe.env

Use --host "*" to allow any machine (not recommended — drops the copy lock).
"""
from __future__ import annotations

import argparse
import json
import sys
import uuid
from datetime import datetime, timedelta, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
PROBE_DIR = HERE.parent
sys.path.insert(0, str(PROBE_DIR))

from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey

from security import hostid
from security.license import mint_license

KEYS_DIR = PROBE_DIR / "keys"
PRIVATE_PEM = KEYS_DIR / "intrynx_license_private.pem"
PUBLIC_PEM = KEYS_DIR / "intrynx_license_public.pem"
EMBEDDED = PROBE_DIR / "security" / "embedded_key.py"


def cmd_keygen(args: argparse.Namespace) -> int:
    KEYS_DIR.mkdir(parents=True, exist_ok=True)
    if PRIVATE_PEM.exists() and not args.force:
        print(f"Refusing to overwrite {PRIVATE_PEM} (use --force).")
        return 1
    priv = Ed25519PrivateKey.generate()
    priv_pem = priv.private_bytes(
        serialization.Encoding.PEM, serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption())
    pub_pem = priv.public_key().public_bytes(
        serialization.Encoding.PEM, serialization.PublicFormat.SubjectPublicKeyInfo)
    PRIVATE_PEM.write_bytes(priv_pem)
    PRIVATE_PEM.chmod(0o600)
    PUBLIC_PEM.write_bytes(pub_pem)
    EMBEDDED.write_text(
        '"""Embedded license-verification public key (generated by tools/mint_license.py).\n'
        'Safe to ship — it can only VERIFY licenses, never mint them."""\n\n'
        f"PUBLIC_KEY_PEM = {pub_pem!r}\n")
    print(f"Private key : {PRIVATE_PEM}   (KEEP SECRET — never ship to a client)")
    print(f"Public key  : {PUBLIC_PEM}")
    print(f"Embedded in : {EMBEDDED}")
    return 0


def cmd_hostid(_: argparse.Namespace) -> int:
    print(hostid.host_fingerprint())
    return 0


def cmd_mint(args: argparse.Namespace) -> int:
    if not PRIVATE_PEM.exists():
        print(f"No private key at {PRIVATE_PEM}. Run 'keygen' first.")
        return 1
    priv = serialization.load_pem_private_key(PRIVATE_PEM.read_bytes(), password=None)
    now = datetime.now(timezone.utc)
    if args.expires:
        expires = args.expires
    else:
        expires = (now + timedelta(days=args.days)).isoformat()
    payload = {
        "v": 1,
        "license_id": args.license_id or uuid.uuid4().hex[:12],
        "customer": args.customer,
        "host_fingerprint": args.host,
        "issued_at": now.isoformat(),
        "expires_at": expires,
    }
    if args.name:
        payload["probe_name"] = args.name
    if args.tenant:
        payload["tenant"] = args.tenant
    if args.segments:
        payload["network_segments"] = [s.strip() for s in args.segments.split(",") if s.strip()]

    token = mint_license(payload, priv)
    if args.out:
        Path(args.out).write_text(token)
        print(f"Wrote license to {args.out}")
    print("\n# Paste into probe.env:")
    print(f"PROBE_LICENSE={token}\n")
    print("# Details:", json.dumps(payload, indent=2))
    return 0


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description="Intrynx license tool (vendor-side)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    kg = sub.add_parser("keygen", help="create the signing keypair + embed the public key")
    kg.add_argument("--force", action="store_true", help="overwrite an existing private key")
    kg.set_defaults(func=cmd_keygen)

    hi = sub.add_parser("hostid", help="print this machine's fingerprint")
    hi.set_defaults(func=cmd_hostid)

    mt = sub.add_parser("mint", help="mint a license token")
    mt.add_argument("--customer", required=True, help="customer / company name")
    mt.add_argument("--host", default="*", help="host fingerprint to lock to (or '*' for any)")
    mt.add_argument("--days", type=int, default=365, help="validity in days (default 365)")
    mt.add_argument("--expires", help="explicit ISO expiry (overrides --days)")
    mt.add_argument("--name", help="probe display name")
    mt.add_argument("--tenant", help="tenant id")
    mt.add_argument("--segments", help="comma-separated allowed CIDRs (informational)")
    mt.add_argument("--license-id", help="explicit license id")
    mt.add_argument("--out", help="also write the token to this file")
    mt.set_defaults(func=cmd_mint)

    args = ap.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
