"""Probe security: host-locked deployment licensing + host-bound state.

The agent calls :func:`check_license` once at startup. A copied probe folder run
on another machine, or with a missing/expired/tampered license, is refused with a
plain-English message (``LicenseError.friendly``).
"""
from __future__ import annotations

import os
from pathlib import Path

from . import hostid
from .license import (License, LicenseError, LicenseMissing, verify_license)
from .state import decrypt_state, encrypt_state

__all__ = ["hostid", "License", "LicenseError", "check_license",
           "load_license_token", "encrypt_state", "decrypt_state"]


class LicenseBuildError(LicenseError):
    friendly = ("This probe build is missing its verification key and cannot start. "
                "Contact your Intrynx administrator for a correctly built probe.")


def _embedded_public_key() -> bytes | None:
    try:
        from .embedded_key import PUBLIC_KEY_PEM  # generated by tools/mint_license.py keygen
        return PUBLIC_KEY_PEM
    except Exception:
        return None


def load_license_token() -> str | None:
    """Find the license: PROBE_LICENSE env, LICENSE_FILE path, or ./license.key."""
    tok = os.environ.get("PROBE_LICENSE")
    if tok and tok.strip():
        return tok.strip()
    path = os.environ.get("LICENSE_FILE")
    candidates = [Path(path)] if path else []
    candidates.append(Path(__file__).resolve().parent.parent / "license.key")
    for c in candidates:
        try:
            v = c.read_text().strip()
            if v:
                return v
        except OSError:
            continue
    return None


def check_license(*, host_fp: str | None = None) -> License:
    """Verify the deployment license for this machine. Raises ``LicenseError``."""
    pub = _embedded_public_key()
    if pub is None:
        raise LicenseBuildError()
    return verify_license(load_license_token(), pub, host_fp or hostid.host_fingerprint())
