"""Embedded license-verification public key (generated by tools/mint_license.py).
Safe to ship — it can only VERIFY licenses, never mint them."""

PUBLIC_KEY_PEM = b'-----BEGIN PUBLIC KEY-----\nMCowBQYDK2VwAyEAgtGLlq/7TI7BYxGraJq1sJMmppk6ycbVgMPZB4xiPy8=\n-----END PUBLIC KEY-----\n'
